# Generated by Django 2.2.16 on 2022-10-04 22:59

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Введите год релиза', validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
